apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: update-replicaset
  namespace: p-go-update
  labels:
    app: update-persona
spec:
  replicas: 2
  selector:
    matchLabels:
      app: update-persona
  template:
    metadata:
      labels:
        app: update-persona
    spec:
      nodeSelector:
        workload: update
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: update-container
          image: danysoftdev/p-go-update:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mongo-update-secret